// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"backend/internal/controller"
	"backend/internal/repository"
	"backend/internal/service"
)

// Injectors from user_wire.go:

func InitUserRouterHandler() (*controller.UserController, error) {
	iUserRepository := repository.NewUserRepository()
	iUserService := service.NewUserService(iUserRepository)
	iAuthService := service.NewAuthService()
	userController := controller.NewUserController(iUserService, iAuthService)
	return userController, nil
}
