server:
  port: 8080
  mode: "dev"

postgres:
  host: 116.118.50.253
  port: 5433
  username: admin
  password: admin
  dbname: mtshop
  sslmode: disable
  maxIdleConns: 10
  maxOpenConns: 100
  connMaxLifetime: 3600

logger:
  log_level: debug
  file_log_name: ""
  max_backups: 30
  max_age: 7
  max_size: 1024
  compress: true
