// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: condition_q.sql

package database

import (
	"context"
	"encoding/json"
)

const createCondition = `-- name: CreateCondition :exec
INSERT INTO conditions (field, operator, value) VALUES ($1, $2, $3)
`

type CreateConditionParams struct {
	Field    ConditionField
	Operator ComparisonOperator
	Value    json.RawMessage
}

func (q *Queries) CreateCondition(ctx context.Context, arg CreateConditionParams) error {
	_, err := q.db.ExecContext(ctx, createCondition, arg.Field, arg.Operator, arg.Value)
	return err
}
