// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: variants_query.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createProductVariant = `-- name: CreateProductVariant :exec
INSERT INTO product_variants (name, status) VALUES ($1, $2)
`

type CreateProductVariantParams struct {
	Name   string
	Status NullVariantsStatus
}

func (q *Queries) CreateProductVariant(ctx context.Context, arg CreateProductVariantParams) error {
	_, err := q.db.ExecContext(ctx, createProductVariant, arg.Name, arg.Status)
	return err
}

const deleteProductVariantById = `-- name: DeleteProductVariantById :exec
DELETE FROM product_variants
WHERE id = $1
`

func (q *Queries) DeleteProductVariantById(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteProductVariantById, id)
	return err
}

const getAllProductVariants = `-- name: GetAllProductVariants :many
SELECT id, name, status, created_at, updated_at FROM product_variants
WHERE (name ILIKE '%' || $1 || '%' OR $1 IS NULL)
    AND (status = $2 OR $2 IS NULL)
ORDER BY updated_at DESC
`

type GetAllProductVariantsParams struct {
	Column1 sql.NullString
	Status  NullVariantsStatus
}

func (q *Queries) GetAllProductVariants(ctx context.Context, arg GetAllProductVariantsParams) ([]ProductVariant, error) {
	rows, err := q.db.QueryContext(ctx, getAllProductVariants, arg.Column1, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductVariant
	for rows.Next() {
		var i ProductVariant
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductVariantById = `-- name: GetProductVariantById :one
SELECT id, name, status, created_at, updated_at FROM product_variants
WHERE id = $1
`

func (q *Queries) GetProductVariantById(ctx context.Context, id uuid.UUID) (ProductVariant, error) {
	row := q.db.QueryRowContext(ctx, getProductVariantById, id)
	var i ProductVariant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProductVariant = `-- name: UpdateProductVariant :exec
UPDATE product_variants
SET name = $1, status = $2
WHERE id = $3
`

type UpdateProductVariantParams struct {
	Name   string
	Status NullVariantsStatus
	ID     uuid.UUID
}

func (q *Queries) UpdateProductVariant(ctx context.Context, arg UpdateProductVariantParams) error {
	_, err := q.db.ExecContext(ctx, updateProductVariant, arg.Name, arg.Status, arg.ID)
	return err
}
