// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: vendor_q.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const addVendor = `-- name: AddVendor :exec
INSERT INTO vendors (user_id,
                     full_name,
                     email,
                     phone_number,
                     store_name,
                     description,
                     address,
                     created_by,
                     updated_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type AddVendorParams struct {
	UserID      uuid.UUID
	FullName    string
	Email       string
	PhoneNumber string
	StoreName   string
	Description sql.NullString
	Address     string
	CreatedBy   uuid.UUID
	UpdatedBy   uuid.UUID
}

func (q *Queries) AddVendor(ctx context.Context, arg AddVendorParams) error {
	_, err := q.db.ExecContext(ctx, addVendor,
		arg.UserID,
		arg.FullName,
		arg.Email,
		arg.PhoneNumber,
		arg.StoreName,
		arg.Description,
		arg.Address,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	return err
}

const getVendorByUUID = `-- name: GetVendorByUUID :one
SELECT id, user_id, full_name, email, phone_number, store_name, status, description, address, created_at, updated_at, created_by, updated_by FROM vendors
WHERE vendors.user_id = $1
`

func (q *Queries) GetVendorByUUID(ctx context.Context, userID uuid.UUID) (Vendor, error) {
	row := q.db.QueryRowContext(ctx, getVendorByUUID, userID)
	var i Vendor
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FullName,
		&i.Email,
		&i.PhoneNumber,
		&i.StoreName,
		&i.Status,
		&i.Description,
		&i.Address,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const updateStatus = `-- name: UpdateStatus :exec
UPDATE vendors
SET status = $1
WHERE user_id = $2
`

type UpdateStatusParams struct {
	Status VendorsStatus
	UserID uuid.UUID
}

func (q *Queries) UpdateStatus(ctx context.Context, arg UpdateStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateStatus, arg.Status, arg.UserID)
	return err
}
